### ISSUE TITLE
Temp fix for unimplemented API calls

### ISSUE THREAD

**Issue by leekelleher** [UmbrellaInc/FalconSharp#1]
For those API calls that haven't been implemented yet, we could use a custom exception to highlight that a pull-request would be appreciated.

See @aaronpowell's gist for the `PullRequestRequiredException` idea:
https://gist.github.com/aaronpowell/2708280

**Comment by aaronpowell** [comment]
FYI - It's on NuGet - https://www.nuget.org/packages/PullRequestRequiredException/

**Comment by leekelleher** [comment]
Cool, thanks @aaronpowell :+1: (450 package downloads, nice! :sunglasses:)
